language: php

sudo: false

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master

php:
  - 5.6
  - 7.0

env:
  matrix:
    - LUMEN_FOLDER=lumen-5.2
    - LUMEN_FOLDER=lumen-5.3
    - LUMEN_FOLDER=lumen-5.4
    - LUMEN_FOLDER=lumen-5.5
    - LUMEN_FOLDER=lumen-5.6

matrix:
  exclude:
    - php: 5.6
      env: LUMEN_FOLDER=lumen-5.5
    - php: 5.6
      env: LUMEN_FOLDER=lumen-5.6
    - php: 7.0
      env: LUMEN_FOLDER=lumen-5.6

before_install:
  - cd tests/$LUMEN_FOLDER

install:
  - travis_retry composer update --no-suggest --no-interaction

script:
  - vendor/bin/phpunit