language: php

sudo: false

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master

php:
  - 5.6
  - 7.0

env:
  matrix:
    - LUMEN_FOLDER=lumen-5.2

before_install:
  - composer self-update --stable --no-interaction
  - cd tests/$LUMEN_FOLDER

install:
  - travis_retry composer update --no-suggest --no-interaction

before_script:
  - cd tests/$LUMEN_FOLDER

script:
  - vendor/bin/phpunit